# Generated by Django 6.0.1 on 2026-03-19 19:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cultural', 'Cultural'), ('technical', 'Technical'), ('sports', 'Sports'), ('nss', 'NSS')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('attendees', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
