# Generated by Django 6.0.1 on 2026-04-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_is_team_event_event_max_team_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity_limited',
            field=models.BooleanField(default=True),
        ),
    ]
