# Generated by Django 6.0.1 on 2026-04-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_capacity_limited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('cultural', 'Cultural'), ('technical', 'Technical'), ('sports', 'Sports'), ('nss', 'NSS'), ('other', 'Other')], max_length=20),
        ),
    ]
