# Generated by Django 6.0.1 on 2026-04-05 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('college', models.CharField(blank=True, max_length=180)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('year_of_study', models.CharField(blank=True, max_length=20)),
                ('section', models.CharField(blank=True, max_length=20)),
                ('roll_no', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
