# Generated by Django 6.0.1 on 2026-04-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_phone_otp_code_profile_phone_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_reset_otp_code',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_reset_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
