# Generated by Django 6.0.1 on 2026-04-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_password_reset_otp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_reset_otp_code',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_reset_otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
