"""
Django settings for FestNest project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

DJANGO_ENV = os.getenv('DJANGO_ENV', 'development').lower()

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DJANGO_ENV == 'production':
        raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set in production.')
    SECRET_KEY = 'dev-insecure-key-change-me'

# SECURITY WARNING: don't run with debug turned on in production!
debug_raw = os.getenv('DJANGO_DEBUG')
if debug_raw is None:
    DEBUG = DJANGO_ENV != 'production'
else:
    DEBUG = debug_raw.lower() in ('1', 'true', 'yes', 'on')

if DJANGO_ENV == 'production' and DEBUG:
    raise ImproperlyConfigured('DJANGO_DEBUG must be false in production.')

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
    if host.strip()
]
render_external_hostname = os.getenv('RENDER_EXTERNAL_HOSTNAME', '').strip()
if render_external_hostname and render_external_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_external_hostname)
if DJANGO_ENV != 'production' and 'testserver' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('testserver')
if DJANGO_ENV == 'production' and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS must be set in production.')

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]
if render_external_hostname:
    render_origin = f'https://{render_external_hostname}'
    if render_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(render_origin)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'events',
    'accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FestNest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FestNest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

database_url = os.getenv('DATABASE_URL', '').strip()
db_engine = os.getenv('DJANGO_DB_ENGINE', '').strip()
if database_url:
    DATABASES['default'] = dj_database_url.parse(database_url, conn_max_age=600, ssl_require=True)
elif db_engine:
    db_name = os.getenv('DJANGO_DB_NAME', '').strip()
    if not db_name:
        raise ImproperlyConfigured('DJANGO_DB_NAME must be set when DJANGO_DB_ENGINE is provided.')
    DATABASES['default'] = {
        'ENGINE': db_engine,
        'NAME': db_name,
        'USER': os.getenv('DJANGO_DB_USER', '').strip(),
        'PASSWORD': os.getenv('DJANGO_DB_PASSWORD', '').strip(),
        'HOST': os.getenv('DJANGO_DB_HOST', '').strip() or 'localhost',
        'PORT': os.getenv('DJANGO_DB_PORT', '').strip(),
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('DJANGO_TIME_ZONE', 'Asia/Kolkata')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'whitenoise.storage.CompressedManifestStaticFilesStorage'
            if DJANGO_ENV == 'production'
            else 'django.contrib.staticfiles.storage.StaticFilesStorage'
        ),
    },
}

use_s3 = os.getenv('DJANGO_USE_S3', 'false').lower() in ('1', 'true', 'yes', 'on')
if use_s3:
    aws_bucket_name = os.getenv('DJANGO_AWS_STORAGE_BUCKET_NAME', '').strip()
    aws_s3_endpoint_url = os.getenv('DJANGO_AWS_S3_ENDPOINT_URL', '').strip()
    aws_access_key_id = os.getenv('DJANGO_AWS_ACCESS_KEY_ID', '').strip()
    aws_secret_access_key = os.getenv('DJANGO_AWS_SECRET_ACCESS_KEY', '').strip()
    aws_default_acl = os.getenv('DJANGO_AWS_DEFAULT_ACL', '').strip() or None
    if not aws_bucket_name:
        raise ImproperlyConfigured('DJANGO_AWS_STORAGE_BUCKET_NAME must be set when DJANGO_USE_S3 is enabled.')
    if not aws_s3_endpoint_url:
        raise ImproperlyConfigured('DJANGO_AWS_S3_ENDPOINT_URL must be set when DJANGO_USE_S3 is enabled.')
    if not aws_access_key_id or not aws_secret_access_key:
        raise ImproperlyConfigured(
            'DJANGO_AWS_ACCESS_KEY_ID and DJANGO_AWS_SECRET_ACCESS_KEY must be set when DJANGO_USE_S3 is enabled.',
        )

    AWS_STORAGE_BUCKET_NAME = aws_bucket_name
    AWS_S3_ENDPOINT_URL = aws_s3_endpoint_url
    AWS_ACCESS_KEY_ID = aws_access_key_id
    AWS_SECRET_ACCESS_KEY = aws_secret_access_key
    AWS_S3_REGION_NAME = os.getenv('DJANGO_AWS_S3_REGION_NAME', '').strip() or None
    AWS_DEFAULT_ACL = aws_default_acl
    AWS_QUERYSTRING_AUTH = os.getenv('DJANGO_AWS_QUERYSTRING_AUTH', 'false').lower() in (
        '1',
        'true',
        'yes',
        'on',
    )
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_ADDRESSING_STYLE = os.getenv('DJANGO_AWS_S3_ADDRESSING_STYLE', 'path')
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3.S3Storage',
        },
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

LOGIN_URL = '/login/'

DEFAULT_FROM_EMAIL = os.getenv('DJANGO_DEFAULT_FROM_EMAIL', 'no-reply@festnest.local')
EMAIL_BACKEND = os.getenv(
    'DJANGO_EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.getenv('DJANGO_EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('DJANGO_EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('DJANGO_EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('DJANGO_EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('DJANGO_EMAIL_USE_TLS', 'true').lower() in ('1', 'true', 'yes', 'on')
EMAIL_USE_SSL = os.getenv('DJANGO_EMAIL_USE_SSL', 'false').lower() in ('1', 'true', 'yes', 'on')

if DJANGO_ENV == 'production':
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv(
        'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS',
        'true',
    ).lower() in ('1', 'true', 'yes', 'on')
    SECURE_HSTS_PRELOAD = os.getenv('DJANGO_SECURE_HSTS_PRELOAD', 'true').lower() in (
        '1',
        'true',
        'yes',
        'on',
    )
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = os.getenv('DJANGO_SECURE_SSL_REDIRECT', 'true').lower() in (
        '1',
        'true',
        'yes',
        'on',
    )
    SECURE_REFERRER_POLICY = os.getenv('DJANGO_SECURE_REFERRER_POLICY', 'same-origin')
    if os.getenv('DJANGO_SECURE_PROXY_SSL_HEADER'):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
